---
title: "Code Book"
author: "Karl Petersen"
date: "2/11/2021"
output: 
    html_document:
    keep_md: yes
---

## Project Description
Getting and Cleaning Data Course Project - Karl Petersen

##  Study design and data processing

###  Collection of the raw data
The data  for this project was collected for a study 'Human Activity Recognition Using SmartPhones'.
  You can find more information about the data set here:
  http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

## Creating the tidy datafile

###  Guide to create the tidy data file
Description on how to create the tidy data file 

* Download the data for the training and test data sets
     +  X_train.txt
     +  y_train.txt
     +  subject_train.txt
     +  X_test.txt
     +  y_test.txt
     +  subject_test.txt"
     +  features.txt
     + activity_labels.txt
*  Load all the data files into dataframes so they can be merged to create a complete data set
    +  X_train.txt as dataframe 'xtrain'
    +  y_train.txt as dataframe 'ytrain'
    +  subject_train.txt as dataframe 'subjecttrain'
    +  X_test.txt as dataframe 'xtest'
    +  y_test.txt as dataframe 'ytest'
    +  subject_test.txt" as dataframe 'subjecttest' 
    +  features.txt as dataframe 'featureLabels'
    +  activity_labels.txt as dataframe 'activityLabels'
*  Combine the training dataframes into a single dataframe(using cbind)
    +    xtrain
    +    ytrain
    +    subjecttrain
*  Combine the test data frames into a single dataframe (using cbind)
    +    xtest
    +    ytest
    +    subjecttest
*  Merge the training and test dataframes from step 3 and 4 together (using rbind)  
*  Create list of featureLabels to use for the column headings of the dataframe created in step 5
*  Remove special characters from the featureLabels to make working with the data easier (tidy column headings)
*  Add them featureLabels as columnn headings (using colnames function)
*  Add the activity labels to the large dataframe create in step five by joining on the id's
*  Select the columns from the dataframe that contain mean and std (mean and standard deviation) into a subset dataframe
*  Calculate the average of all the columns of the new subset dataframe grouping by the subjectID and activity description and assigne to an aggregate data frame
*  Write out aggregated data to a csv file.  

###  Cleaning of the data
It is important to remove special characters from the column headings to make working with the data easier.  You must also update the column headings because there are duplicate column names.    [link to the readme document that describes the code in greater detail]()

##  Description of the variables in the tiny_data.txt file
General description of the file including:
 - Table Dimenstion
    rows =180, columns = 88
 - This data represents the averages for the columns that include the mean and standard deviation measures from the 'Human Activity Recognition Using SmartPhones dtat sent'


```{r message=FALSE, results='asis', echo=FALSE}
library(readr)
library(knitr)
tidydatasetCodeBook <- read_csv("tidydatasetCodeBook.csv")
knitr::kable(tidydatasetCodeBook, caption = "Tidydataset")
```


